server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false - 表示不获取服务列表
    fetch-registry: false
    service-url:
      # 注册到 7002 服务上
      defaultZone: http://eureka7002.com:7002/eureka/

spring:
  application:
    name: Eureka-Server